---
- hosts: airflow_servers
  become: true
  vars_files:
    - ../secrets.yml

  vars:
    airflow_home: /home/airflow

  tasks:
    - name: Установка необходимых пакетов
      apt:
        name:
          - python3-pip
          - libpq-dev
          - python3-dev
          - build-essential
          - python3-venv
        state: present
      when: ansible_os_family == "Debian"

    - name: Создание пользователя airflow
      user:
        name: airflow
        shell: /bin/bash
        home: "{{ airflow_home }}"
        state: present

    - name: Создание виртуального окружения
      command: python3 -m venv {{ airflow_home }}/venv
      args:
        creates: "{{ airflow_home }}/venv"

    - name: Копирование файла requirements.txt на удаленный сервер
      copy:
        src: ../airflow/requirements.txt  # Убедитесь, что этот путь правильный
        dest: "{{ airflow_home }}/requirements.txt"  # Путь на удаленном сервере

    - name: Установка Apache Airflow в виртуальном окружении
      pip:
        requirements: "{{ airflow_home }}/requirements.txt"
        virtualenv: "{{ airflow_home }}/venv"
      environment:
        VIRTUAL_ENV: "{{ airflow_home }}/venv"
        PATH: "{{ airflow_home }}/venv/bin:{{ ansible_env.PATH }}"

    - name: Создание необходимых директорий
      file:
        path: "{{ airflow_home }}/{{ item }}"
        state: directory
        owner: airflow
        group: airflow
        mode: '0755'
      loop:
        - dags
        - logs
        - plugins

    - name: Создание файла конфигурации Airflow
      template:
        src: airflow.cfg.j2
        dest: "{{ airflow_home }}/airflow.cfg"
      notify:
        - инициализация базы данных

    - name: Создание systemd unit файла для Airflow webserver
      copy:
        dest: /etc/systemd/system/airflow-webserver.service
        content: |
          [Unit]
          Description=Airflow webserver
          After=network.target

          [Service]
          User=airflow
          Group=airflow
          WorkingDirectory={{ airflow_home }}
          Environment="PATH={{ airflow_home }}/venv/bin"
          ExecStart={{ airflow_home }}/venv/bin/airflow webserver --port 8080
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Перезагрузка systemd
      command: systemctl daemon-reload

    - name: Запуск Airflow webserver
      systemd:
        name: airflow-webserver
        state: started
        enabled: true

    - name: Запуск Airflow scheduler
      shell: "{{ airflow_home }}/venv/bin/airflow scheduler -D"
      args:
        chdir: "{{ airflow_home }}"
      async: 10
      poll: 0

  handlers:
    - name: инициализация базы данных
      command: "{{ airflow_home }}/venv/bin/airflow db init"
      args:
        chdir: "{{ airflow_home }}"
